### PR TITLE
Monorepo + Typescript + some es6 cleanup

### PR DESCRIPTION
**Pull request by chriseppstein**
Creates a monorepo containing:
* eyeglass
* [broccoli-eyeglass][broccoli-eyeglass]
* [ember-cli-eyeglass][ember-cli-eyeglass]

For just eyeglass core it:
* Converts the project to typescript (without very much strictness yet enabled and very few types defined).
* Adopts class definitions instead of function + prototype manipulation in many places
* Uses import statements instead of require and export statements instead of `module.exports`.

[broccoli-eyeglass]: https://github.com/sass-eyeglass/broccoli-eyeglass
[ember-cli-eyeglass]: https://github.com/sass-eyeglass/ember-cli-eyeglass

### CODE REVIEW

**Comment by chriseppstein** [comment]
Note that I used `git subtree` to import these projects which preserves git history and attribution as well as enabling us to continue to pull from the main repo until this lands.

**Comment by stefanpenner** [comment]
looks one one failed test:

```
not ok 2 Chrome 62.0 - [97 ms] - Acceptance | eyeglass: visiting /eager
    ---
        actual: >
            false
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:50:14)
                at <anonymous>
        message: >
            expected:
            
            /eager/assets/img/test.jpg
            
            to be contained within:
            
            http://localhost:7357/assets/img/test.jpg
            
        negative: >
            false
        Log: |
    ...
```

**Comment by stefanpenner** [comment]
Whats the ETA for this?

**Comment by chriseppstein** [comment]
@stefanpenner The failure is the failing test case that @chadhietala provided in https://github.com/sass-eyeglass/ember-cli-eyeglass/pull/50. It is and expected failure and I am going to disable that test for now.

Regarding ETA, I'd like to land this sooner than later and migrate at least these three projects  to the linkedin github organization. Please let me know if you have any reservations.

**Comment by stefanpenner** [comment]
> Regarding ETA, I'd like to land this sooner than later and migrate at least these three projects to the linkedin github organization. Please let me know if you have any reservations.

I agree, my only reservation would be letting this sit for too long.

**Pull request merged**
