### PR TITLE
add support for including modules manually

### PR DESCRIPTION
**Pull request by eoneill**
Per #96, this would support adding modules manually via JavaScript (not discovered through `package.json`).

I'm still not entirely convinced this is a good idea, but it's easy enough to support I'm not too concerned.

The interface is to pass the modules (objects) via the eyeglass options:

```js
var eyeglass = new Eyeglass({
  eyeglass: {
    modules: [
      {
        name: "my-module",
        main: function(eyeglass, sass) {
          return {
            sassDir: ...,
            functions: ....,
            assets: ....
          };
        }
      },
      ...
    ]
  }
});
```

### CODE REVIEW

**Comment by chriseppstein** [comment]
Looks good, we need to add docs for this.

**Comment by eoneill** [comment]
Latest update improves `EyeglassModule` constructor to do the heavy lifting.

```js
var mod = new EyeglassModule({ ... });
mod.init(eyeglass, sass);
```

This will normalize the module interface and the `init()` will execute the `main` (if present). This is useful so we don't have to `if (mod.main) { require(mod.main)(eyeglass, sass); }` in multiple places and makes the interface more consistent overall.

This updated interface now also allows us to manually add a module with a path:

```js
var eyeglass = new Eyeglass({
   ...,
   eyeglass: {
    modules: [{
      path: path.join(__dirname, "bower_components/my-bower-module")
    }]
  }
});
```

Finally, this will allow modules to expose custom JavaScript interfaces. e.g.
```js
// module-foo/eyeglass-exports.js
module.exports = function(eyeglass, sass) {
   return {
    ...
    doSomething: function() { ... }
  }
};
```
```js
var eyeglass = new Eyeglass(...);
eyeglass.modules.find("module-foo").doSomething(...);
```

**Comment by chriseppstein** [comment]
@eoneill what is the use case(s) you have in mind for the "custom JavaScript interfaces"

**Comment by eoneill** [comment]
http://www.restylecss.com/documentation/understanding-grammar/

Currently, in reSTYLE, I abuse the `options` object to expose an `addGrammarEngine` method.

With this new approach, I would expose the method on the `eyeglass-exports`:

```js
module.exports = function(...) {
  return {
    ...
    addGrammarEngine: function(...) {}
  }
};
```
And consumers would access this via...
```js
eyeglass.modules.find("restyle").addGrammarEngine(...)
```

**Comment by chriseppstein** [comment]
See my comments on #96. This exposes a new public API of things that used to be only internal. I don't want to do this just because it's "easy" -- there has to be a compelling use case and I'm still not convinced of one. I want to hold back on merging this -- I don't know how to review a feature without having the context of the goals clear in my mind.

**Comment by chriseppstein** [comment]
Closing this, after #112 landed, any features from this PR need to be reworked and resubmitted. I'm also still not sold on the idea of manual modules.

**Pull request closed without merging**
