### PR TITLE
[dependencies] bump dependencies, use eslint, mocha and nyc directly

### PR DESCRIPTION
**Pull request by gabrielcsapo**
- updates dependencies

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
fixing conflicts now

**Comment by gabrielcsapo** [comment]
updating the travis file with the versions of node eyeglass supports now works

**Comment by stefanpenner** [comment]
LGTM, this will require a major version bump. I'll cut shortly.

**Comment by stefanpenner** [comment]
released as v2.0.0 🎉

**Comment by gabrielcsapo** [comment]
❤️ 🎉

**Pull request merged**
